// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/model/model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CREATE
type CreateRequest struct {
	Data                 *CreateRequestData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" bson:"data,omitempty"`
	Options              map[string]string  `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetData() *CreateRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateRequest) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

type CreateRequestData struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" bson:"type,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-"`
}

func (m *CreateRequestData) Reset()         { *m = CreateRequestData{} }
func (m *CreateRequestData) String() string { return proto.CompactTextString(m) }
func (*CreateRequestData) ProtoMessage()    {}
func (*CreateRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{1}
}

func (m *CreateRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestData.Unmarshal(m, b)
}
func (m *CreateRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestData.Marshal(b, m, deterministic)
}
func (m *CreateRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestData.Merge(m, src)
}
func (m *CreateRequestData) XXX_Size() int {
	return xxx_messageInfo_CreateRequestData.Size(m)
}
func (m *CreateRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestData proto.InternalMessageInfo

func (m *CreateRequestData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateRequestData) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// UPDATE
type UpdateRequest struct {
	Data                 *UpdateRequestData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" bson:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{2}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetData() *UpdateRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRequestData struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" bson:"type,omitempty"`
	Id                   string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-"`
}

func (m *UpdateRequestData) Reset()         { *m = UpdateRequestData{} }
func (m *UpdateRequestData) String() string { return proto.CompactTextString(m) }
func (*UpdateRequestData) ProtoMessage()    {}
func (*UpdateRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{3}
}

func (m *UpdateRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequestData.Unmarshal(m, b)
}
func (m *UpdateRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequestData.Marshal(b, m, deterministic)
}
func (m *UpdateRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequestData.Merge(m, src)
}
func (m *UpdateRequestData) XXX_Size() int {
	return xxx_messageInfo_UpdateRequestData.Size(m)
}
func (m *UpdateRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequestData proto.InternalMessageInfo

func (m *UpdateRequestData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequestData) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// FIND
type FindRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" bson:"type,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" bson:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty" bson:"limit,omitempty"`
	SortBy               string   `protobuf:"bytes,4,opt,name=sortBy,proto3" json:"sortBy,omitempty" bson:"sortBy,omitempty"`
	Filter               []byte   `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty" bson:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{4}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FindRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *FindRequest) GetFilter() []byte {
	if m != nil {
		return m.Filter
	}
	return nil
}

type FindResponse struct {
	Metadata             *Metadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty" bson:"metadata,omitempty"`
	Data                 []*Response `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" bson:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{5}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *FindResponse) GetData() []*Response {
	if m != nil {
		return m.Data
	}
	return nil
}

type Metadata struct {
	Paginate             *Paginate `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty" bson:"paginate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{6}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetPaginate() *Paginate {
	if m != nil {
		return m.Paginate
	}
	return nil
}

type Paginate struct {
	TotalCount           int32    `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	PageCount            int32    `protobuf:"varint,2,opt,name=pageCount,proto3" json:"pageCount,omitempty" bson:"pageCount,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty" bson:"page,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty" bson:"limit,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty" bson:"sortBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Paginate) Reset()         { *m = Paginate{} }
func (m *Paginate) String() string { return proto.CompactTextString(m) }
func (*Paginate) ProtoMessage()    {}
func (*Paginate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{7}
}

func (m *Paginate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paginate.Unmarshal(m, b)
}
func (m *Paginate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paginate.Marshal(b, m, deterministic)
}
func (m *Paginate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paginate.Merge(m, src)
}
func (m *Paginate) XXX_Size() int {
	return xxx_messageInfo_Paginate.Size(m)
}
func (m *Paginate) XXX_DiscardUnknown() {
	xxx_messageInfo_Paginate.DiscardUnknown(m)
}

var xxx_messageInfo_Paginate proto.InternalMessageInfo

func (m *Paginate) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *Paginate) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

func (m *Paginate) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Paginate) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Paginate) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

// TRANSACTIONS BY ID
type ByIdRequest struct {
	Data                 *ByIdRequestData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" bson:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *ByIdRequest) Reset()         { *m = ByIdRequest{} }
func (m *ByIdRequest) String() string { return proto.CompactTextString(m) }
func (*ByIdRequest) ProtoMessage()    {}
func (*ByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{8}
}

func (m *ByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIdRequest.Unmarshal(m, b)
}
func (m *ByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIdRequest.Marshal(b, m, deterministic)
}
func (m *ByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIdRequest.Merge(m, src)
}
func (m *ByIdRequest) XXX_Size() int {
	return xxx_messageInfo_ByIdRequest.Size(m)
}
func (m *ByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByIdRequest proto.InternalMessageInfo

func (m *ByIdRequest) GetData() *ByIdRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ByIdRequestData struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" bson:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ByIdRequestData) Reset()         { *m = ByIdRequestData{} }
func (m *ByIdRequestData) String() string { return proto.CompactTextString(m) }
func (*ByIdRequestData) ProtoMessage()    {}
func (*ByIdRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{9}
}

func (m *ByIdRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIdRequestData.Unmarshal(m, b)
}
func (m *ByIdRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIdRequestData.Marshal(b, m, deterministic)
}
func (m *ByIdRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIdRequestData.Merge(m, src)
}
func (m *ByIdRequestData) XXX_Size() int {
	return xxx_messageInfo_ByIdRequestData.Size(m)
}
func (m *ByIdRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIdRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_ByIdRequestData proto.InternalMessageInfo

func (m *ByIdRequestData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ByIdRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// RESPONSE
type Response struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" bson:"type,omitempty"`
	Id                   string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5856a62059d3302, []int{10}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "model.CreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "model.CreateRequest.OptionsEntry")
	proto.RegisterType((*CreateRequestData)(nil), "model.CreateRequestData")
	proto.RegisterMapType((map[string]string)(nil), "model.CreateRequestData.AttributesEntry")
	proto.RegisterType((*UpdateRequest)(nil), "model.UpdateRequest")
	proto.RegisterType((*UpdateRequestData)(nil), "model.UpdateRequestData")
	proto.RegisterMapType((map[string]string)(nil), "model.UpdateRequestData.AttributesEntry")
	proto.RegisterType((*FindRequest)(nil), "model.FindRequest")
	proto.RegisterType((*FindResponse)(nil), "model.FindResponse")
	proto.RegisterType((*Metadata)(nil), "model.Metadata")
	proto.RegisterType((*Paginate)(nil), "model.Paginate")
	proto.RegisterType((*ByIdRequest)(nil), "model.ByIdRequest")
	proto.RegisterType((*ByIdRequestData)(nil), "model.ByIdRequestData")
	proto.RegisterType((*Response)(nil), "model.Response")
	proto.RegisterMapType((map[string]string)(nil), "model.Response.AttributesEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModelClient is the client API for Model service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error)
	FindById(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*Response, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	DeleteById(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*Response, error)
}

type modelClient struct {
	cc *grpc.ClientConn
}

func NewModelClient(cc *grpc.ClientConn) ModelClient {
	return &modelClient{cc}
}

func (c *modelClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/model.Model/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/model.Model/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) FindById(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/model.Model/FindById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/model.Model/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) DeleteById(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/model.Model/DeleteById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServer is the server API for Model service.
type ModelServer interface {
	Create(context.Context, *CreateRequest) (*Response, error)
	Update(context.Context, *UpdateRequest) (*Response, error)
	FindById(context.Context, *ByIdRequest) (*Response, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	DeleteById(context.Context, *ByIdRequest) (*Response, error)
}

func RegisterModelServer(s *grpc.Server, srv ModelServer) {
	s.RegisterService(&_Model_serviceDesc, srv)
}

func _Model_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Model/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Model/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Model/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).FindById(ctx, req.(*ByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Model/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_DeleteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).DeleteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Model/DeleteById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).DeleteById(ctx, req.(*ByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Model_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Model",
	HandlerType: (*ModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Model_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Model_Update_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _Model_FindById_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _Model_Find_Handler,
		},
		{
			MethodName: "DeleteById",
			Handler:    _Model_DeleteById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/model/model.proto",
}

func init() { proto.RegisterFile("src/model/model.proto", fileDescriptor_a5856a62059d3302) }

var fileDescriptor_a5856a62059d3302 = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6a, 0xd4, 0x50,
	0x10, 0x36, 0x7f, 0x35, 0x9d, 0xdd, 0xba, 0x76, 0xac, 0x25, 0x2c, 0xa2, 0x6b, 0xbc, 0x59, 0x54,
	0x56, 0xdc, 0x22, 0x6a, 0xa5, 0x88, 0x6d, 0x15, 0xbd, 0x28, 0x4a, 0xc0, 0x7b, 0x4f, 0xcd, 0xb1,
	0x04, 0xb3, 0x49, 0x4c, 0x66, 0x85, 0xe0, 0x0b, 0x88, 0x0f, 0x23, 0x5e, 0x79, 0xed, 0xa3, 0xc9,
	0xf9, 0x49, 0x9a, 0x64, 0x23, 0xb6, 0x17, 0xbd, 0x59, 0xce, 0xcc, 0x7c, 0xdf, 0xcc, 0x9c, 0x6f,
	0xe6, 0x64, 0xe1, 0x7a, 0x91, 0x7f, 0x7c, 0xb0, 0x48, 0x43, 0x1e, 0xab, 0xdf, 0x59, 0x96, 0xa7,
	0x94, 0xa2, 0x23, 0x0d, 0xff, 0xb7, 0x01, 0x1b, 0x07, 0x39, 0x67, 0xc4, 0x03, 0xfe, 0x65, 0xc9,
	0x0b, 0xc2, 0xfb, 0x60, 0x87, 0x8c, 0x98, 0x67, 0x4c, 0x8c, 0xe9, 0x60, 0xee, 0xcd, 0x14, 0xa9,
	0x85, 0x39, 0x64, 0xc4, 0x02, 0x89, 0xc2, 0x67, 0x70, 0x39, 0xcd, 0x28, 0x4a, 0x93, 0xc2, 0x33,
	0x27, 0xd6, 0x74, 0x30, 0xbf, 0xdd, 0x47, 0x98, 0xbd, 0x55, 0x98, 0x97, 0x09, 0xe5, 0x65, 0x50,
	0x31, 0xc6, 0xbb, 0x30, 0x6c, 0x06, 0xf0, 0x2a, 0x58, 0x9f, 0x79, 0x29, 0x2b, 0xaf, 0x07, 0xe2,
	0x88, 0x5b, 0xe0, 0x7c, 0x65, 0xf1, 0x92, 0x7b, 0xa6, 0xf4, 0x29, 0x63, 0xd7, 0x7c, 0x62, 0xf8,
	0xbf, 0x0c, 0xd8, 0x5c, 0x69, 0x0a, 0x11, 0x6c, 0x2a, 0x33, 0xae, 0x53, 0xc8, 0x33, 0xbe, 0x06,
	0x60, 0x44, 0x79, 0x74, 0xbc, 0x24, 0x5e, 0x75, 0x39, 0xfd, 0xd7, 0xb5, 0x66, 0x2f, 0x6a, 0xa8,
	0x6a, 0xb6, 0xc1, 0x1d, 0xef, 0xc1, 0xa8, 0x13, 0x3e, 0x57, 0xcb, 0x7b, 0xb0, 0xf1, 0x3e, 0x0b,
	0xff, 0x2b, 0x75, 0x0b, 0x73, 0x2a, 0xb5, 0xff, 0xc7, 0x80, 0xcd, 0x95, 0x58, 0xef, 0x8d, 0xaf,
	0x80, 0x19, 0x85, 0xba, 0xbe, 0x19, 0x85, 0x1d, 0x05, 0xac, 0x96, 0x02, 0x2b, 0x19, 0x2f, 0x52,
	0x81, 0x6f, 0x30, 0x78, 0x15, 0x25, 0x61, 0x75, 0xff, 0xbe, 0xde, 0x11, 0xec, 0x8c, 0x9d, 0x28,
	0xae, 0x13, 0xc8, 0xb3, 0x48, 0x18, 0x47, 0x8b, 0x88, 0x3c, 0x4b, 0x3a, 0x95, 0x81, 0xdb, 0xb0,
	0x56, 0xa4, 0x39, 0xed, 0x97, 0x9e, 0x2d, 0xf9, 0xda, 0x12, 0xfe, 0x4f, 0x51, 0x4c, 0x3c, 0xf7,
	0x9c, 0x89, 0x31, 0x1d, 0x06, 0xda, 0xf2, 0x3f, 0xc0, 0x50, 0x15, 0x2f, 0xb2, 0x34, 0x29, 0x38,
	0xde, 0x03, 0x77, 0xc1, 0x89, 0x35, 0x26, 0x30, 0xd2, 0x9a, 0x1c, 0x69, 0x77, 0x50, 0x03, 0xf0,
	0x8e, 0x1e, 0x95, 0x5a, 0x9f, 0x0a, 0x58, 0xe5, 0xd2, 0x13, 0x7a, 0x0c, 0x6e, 0x45, 0x15, 0xd9,
	0x33, 0x76, 0x12, 0x25, 0x8c, 0x78, 0x27, 0xfb, 0x3b, 0xed, 0x0e, 0x6a, 0x80, 0xff, 0xc3, 0x00,
	0xb7, 0x72, 0xe3, 0x4d, 0x00, 0x4a, 0x89, 0xc5, 0x07, 0xe9, 0x32, 0x21, 0xc9, 0x75, 0x82, 0x86,
	0x07, 0x6f, 0xc0, 0xba, 0x50, 0x45, 0x85, 0x95, 0x4c, 0xa7, 0x8e, 0x5a, 0x3f, 0xab, 0x4f, 0x3f,
	0xbb, 0x5f, 0x3f, 0xa7, 0xa9, 0x9f, 0xff, 0x14, 0x06, 0xfb, 0xe5, 0x9b, 0x7a, 0x48, 0x77, 0x5b,
	0x4b, 0xba, 0xad, 0x2f, 0xd1, 0x40, 0x34, 0x56, 0xf4, 0x11, 0x8c, 0x3a, 0x81, 0xb3, 0xec, 0xa7,
	0xff, 0xd3, 0x00, 0xb7, 0x1e, 0xcb, 0x59, 0x16, 0xfa, 0x79, 0xcf, 0x42, 0xdf, 0xea, 0xcc, 0xe4,
	0x02, 0xf7, 0x78, 0xfe, 0xdd, 0x04, 0xe7, 0x48, 0x54, 0xc3, 0x87, 0xb0, 0xa6, 0xbe, 0x21, 0xb8,
	0xd5, 0xf7, 0x49, 0x19, 0x77, 0x37, 0xc5, 0xbf, 0x24, 0x28, 0xea, 0xd1, 0xd5, 0x94, 0xd6, 0x1b,
	0xec, 0xa7, 0xb8, 0x62, 0x75, 0x85, 0xb6, 0x88, 0xab, 0x13, 0xe8, 0xa7, 0xd8, 0x82, 0x52, 0xc3,
	0x1b, 0xef, 0x6e, 0x7c, 0xad, 0xe5, 0xab, 0x29, 0x3b, 0x00, 0x87, 0x3c, 0xe6, 0xc4, 0xcf, 0x51,
	0xe7, 0x78, 0x4d, 0xfe, 0x9d, 0xec, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x4d, 0x72, 0xdf,
	0x67, 0x06, 0x00, 0x00,
}
