version: '3.5'
services:
  api:
    container_name: $CATALOG_CONTAINER
    image: $CATALOG_IMAGE
    build:
      context: .
    restart: always
    ports:
      - $CATALOG_PORT:$CATALOG_PORT
    expose:
      - $CATALOG_PORT
    volumes:
      - $CATALOG_VOLUME
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: $MONGO_IMAGE
    container_name: $MONGO_CONTAINER
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: $MONGO_CONTAINER
    expose:
      - $MONGO_PORT
networks:
  default:
    name: $NETWORK 
