package contants

import "os"

var (
	CATALOG_CONTAINER string
	CATALOG_PORT      string
	CATALOG_SERVICE   string

	MONGO_CONTAINER     string
	MONGO_DATABASE_AUTH string
	MONGO_DATABASE      string
	MONGO_PASSWORD      string
	MONGO_USERNAME      string

	STATUS_DELETED string = "STATUS_DELETED"
)

func init() {
	CATALOG_CONTAINER = os.Getenv("CATALOG_CONTAINER")
	CATALOG_PORT = os.Getenv("CATALOG_PORT")
	CATALOG_SERVICE = CATALOG_CONTAINER + ":" + CATALOG_PORT

	MONGO_CONTAINER = os.Getenv("MONGO_CONTAINER")
	MONGO_DATABASE_AUTH = os.Getenv("MONGO_DATABASE_AUTH")
	MONGO_DATABASE = os.Getenv("MONGO_DATABASE")
	MONGO_PASSWORD = os.Getenv("MONGO_PASSWORD")
	MONGO_USERNAME = os.Getenv("MONGO_USER")
}
