package contants

import "os"

var (
	MODEL_CONTAINER string
	MODEL_PORT      string
	MODEL_SERVICE   string

	MONGO_CONTAINER     string
	MONGO_DATABASE_AUTH string
	MONGO_DATABASE      string
	MONGO_PASSWORD      string
	MONGO_USERNAME      string

	STATUS_DELETED string = "STATUS_DELETED"
)

func init() {
	MODEL_CONTAINER = os.Getenv("MODEL_CONTAINER")
	MODEL_PORT = os.Getenv("MODEL_PORT")
	MODEL_SERVICE = MODEL_CONTAINER + ":" + MODEL_PORT

	MONGO_CONTAINER = os.Getenv("MONGO_CONTAINER")
	MONGO_DATABASE_AUTH = os.Getenv("MONGO_DATABASE_AUTH")
	MONGO_DATABASE = os.Getenv("MONGO_DATABASE")
	MONGO_PASSWORD = os.Getenv("MONGO_PASSWORD")
	MONGO_USERNAME = os.Getenv("MONGO_USER")
}
